import type { Home } from '@/payload-types'

/**
 * English fallbacks when CMS / locale data is missing. CMS always wins when present.
 */
export const HOME_DEFAULTS: Partial<Home> = {
  siteName: 'CoffeeLab',
  skipLinkLabel: 'Skip to main content',
  accountAriaLabel: 'Account',
  cartAriaLabel: 'Cart',
  heroKicker: 'LAB PROTOCOL // ACTIVE',
  heroTitleLine1: 'MOLECULAR',
  heroTitleLine2: 'ROASTERY',
  heroSubtitle:
    'Explore the biological frontier of Espresso and Filter extraction via digital synthesis.',
  heroAccentWord1: '',
  heroAccentWord2: '',
  heroPrimaryCtaLabel: 'INITIALIZE_SYSTEM',
  heroPrimaryCtaHref: '#roastery',
  heroSecondaryCtaLabel: 'SECURE_ARCHIVES',
  heroSecondaryCtaHref: '#archives',
  navItems: [
    { label: 'SHOP', href: '#roastery' },
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  laboratoryPhase: 'LABORATORY STORE',
  laboratoryTitle: 'Featured Specimens',
  laboratoryIntro:
    'Curated selection of single-origin coffees and precision-engineered blends. All specimens roasted to order in our molecular laboratory.',
  laboratoryEmptyFilter: 'No specimens match this filter.',
  laboratoryPriceLabel: 'PRICE / 12OZ',
  laboratoryAddToCartAriaTemplate: 'Add {title} to cart',
  storeFilters: [
    { id: 'all', label: 'ALL' },
    { id: 'bestseller', label: 'BESTSELLER' },
    { id: 'single-origin', label: 'SINGLE ORIGIN' },
    { id: 'espresso-blend', label: 'ESPRESSO BLEND' },
    { id: 'rare-varietal', label: 'RARE VARIETAL' },
  ],
  labStats: [
    { value: '50+', label: 'PRODUCTS', icon: 'box' },
    { value: '92.5', label: 'QUALITY SCORE', icon: 'medal' },
    { value: '4.8', label: 'AVG RATING', icon: 'star' },
    { value: '5,200+', label: 'HAPPY CUSTOMERS', icon: 'trend' },
  ],
  protocolEyebrow: 'EXTRACTION PROTOCOL',
  protocolTitle: 'System Calibration',
  brewEspressoLabel: 'ESPRESSO',
  brewFilterLabel: 'FILTER',
  geneticSection: {
    mediaTag: '32% PROFIT RE-INJECTION',
    phase: 'PHASE_01',
    title: 'Direct Genetic Sourcing',
    body:
      'We analyze the DNA of every micro-lot. Our direct relationships ensure farmers receive 3x the standard market rate, securing the future of high-altitude specialty beans.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  thermalSection: {
    mediaTag: '0.05°C VARIANCE LIMIT',
    phase: 'PHASE_02',
    title: 'Thermal Roasting Precision',
    body:
      'Our Loring smart-roasters capture 1,200 data points per second. We hit the exact chemical transition point where acidity transforms into complex sweetness.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  valueSection: {
    mediaTag: '100% COST TRANSPARENCY',
    phase: 'PHASE_03',
    title: 'Transparent Value Index',
    body:
      'No marketing fluff. We open-source our costs. You see the bean price, the logistics, and the roasting energy. Fair pricing, scientifically calculated.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  precisionPhase: 'PRECISION LAB',
  precisionTitle: 'Molecular Customization',
  precisionIntro:
    'Tinker with the chemical variables. As an expert, you control the extraction curves for the filter profile.',
  precisionPanelTitle: 'EXTRACTION LAB',
  precisionStatusPrefix: 'STATUS: ACTIVE //',
  axisRoast: 'ROAST',
  axisAcidity: 'ACIDITY',
  axisBody: 'BODY',
  axisSweetness: 'SWEETNESS',
  axisComplexity: 'COMPLEXITY',
  matrixHeading: 'EXTRACTION MATRIX:',
  matrixTagsEspresso: [
    { text: 'MAILLARD RICHNESS' },
    { text: 'CARAMELIZED FINISH' },
    { text: 'HIGH VISCOSITY' },
  ],
  matrixTagsFilter: [
    { text: 'CITRIC BRIGHTNESS' },
    { text: 'CARAMELIZED FINISH' },
    { text: 'VOLATILE FLAVORS' },
  ],
  synthesizeButton: 'SYNTHESIZE FLAVOR PROFILE',
  scanStats: [
    { template: 'SCAN_UID: X-992' },
    { template: 'BEAM_TEMP: {beam}°C' },
    { template: 'WATER_V: {water}%' },
  ],
  roastSliderLabel: 'Set Roast Target',
  radarAriaLabel: 'Live flavor radar chart',
  flavorNote: 'Flavor profile updates in real-time as roast level changes.',
  blendingPhase: 'GENETIC FUSION',
  blendingTitle: 'The Blending Chamber',
  blendingIntro: 'Synthesis of rare micro-lots optimized for clarity of terroir.',
  blendingTabExpert: 'EXPERT CURATION',
  blendingTabManual: 'MANUAL ASSEMBLY',
  blendingExpertCards: [
    {
      intensityLabel: 'ETHEREAL INTENSITY',
      title: 'Prism Clarity',
      sensoryFilter: '"Tea-like body, jasmine florals, white peach acidity."',
      sensoryEspresso: '"Dense crema, chocolate backbone, concentrated sweetness."',
      geneticBase: 'Ethiopia Yirgacheffe (Washed)',
      methodologyFilter: 'FILTER EXTRACTION',
      methodologyEspresso: 'ESPRESSO EXTRACTION',
      price: '$28.00',
      cta: 'ADD TO CART',
    },
    {
      intensityLabel: 'VIBRANT INTENSITY',
      title: 'Neon Horizon',
      sensoryFilter: '"Vibrant berry notes, sparkling acidity, honey finish."',
      sensoryEspresso: '"Heavy body, caramelized sugars, long syrupy finish."',
      geneticBase: 'Kenya Nyeri + Colombia Pink Bourbon',
      methodologyFilter: 'FILTER EXTRACTION',
      methodologyEspresso: 'ESPRESSO EXTRACTION',
      price: '$25.00',
      cta: 'ADD TO CART',
    },
  ],
  manualAssemblerTitle: 'GENETIC ASSEMBLER',
  manualAssemblerProtocolPrefix: 'PROTOCOL: MANUAL_OVERRIDE //',
  manualRecalibrate: 'RECALIBRATE',
  manualRowsEspresso: [
    { code: 'MOGIANA // SPECIMEN', name: 'Brazilian Santos' },
    { code: 'MALABAR // SPECIMEN', name: 'Indian Monsooned' },
    { code: 'LAB SELECT // SPECIMEN', name: 'Dark Roast Blend' },
  ],
  manualRowsFilter: [
    { code: 'GUJI // SPECIMEN', name: 'Ethiopian Heirloom' },
    { code: 'GEISHA // SPECIMEN', name: 'Panama Geisha' },
    { code: 'LAB SELECT // SPECIMEN', name: 'Light Roast Blend' },
  ],
  saturationLabel: 'SATURATION',
  stabilityLabel: 'STABILITY_CHECK',
  stabilityLocked: 'SYSTEM_LOCKED',
  stabilityCalibrating: 'CALIBRATING...',
  finalizeAssembly: 'FINALIZE ASSEMBLY',
  vaultPhase: 'SENSORY DECOUPLING',
  vaultTitle: 'Classified Vault',
  vaultIntro: 'Access the most exclusive beans in our collection.',
  vaultCuppingLabel: 'CUPPING SCORE',
  vaultSpecimenYear: 'SPECIMEN // 2026',
  vaultMetadataLabel: 'METADATA:',
  vaultMetadataValue: 'ENCRYPTED_FOR_RESEARCHERS',
  vaultPriceLabel: 'SPECIMEN_COST',
  vaultCards: [
    {
      score: '91.5',
      title: 'PROTOCOL X-771',
      label: 'EXPERIMENTAL PROFILE',
      originLine: 'Ethiopia · Heirloom',
      roastLine: 'Light — expressive',
      flavorLine: 'Jasmine, bergamot, nectarine',
      description:
        'A profile that challenges the biological limits of perception. High thermal variability during roast.',
      metadataPill: 'DECRYPTING_BIO_SIGNATURE',
      price: '$32.00',
      addToCartLabel: 'ADD TO CART',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
    {
      score: '89.0',
      title: 'PROTOCOL X-442',
      label: 'ANAEROBIC MICROLOT',
      originLine: 'Undisclosed altitude',
      roastLine: 'Medium — developed',
      flavorLine: 'Cocoa, red berry, molasses',
      description:
        'Sourced from a secret high-altitude plot. Identity hidden to prevent expectation bias.',
      metadataPill: 'DECRYPTING_BIO_SIGNATURE',
      price: '$32.00',
      addToCartLabel: 'ADD TO CART',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
    {
      score: '92.2',
      title: 'PROTOCOL X-901',
      label: 'CARBONIC MACERATION',
      originLine: 'Panama · Gesha',
      roastLine: 'Light — omni',
      flavorLine: 'Tropical, champagne, silk',
      description: 'The pinnacle of our laboratory efforts. Pure molecular expression of terroir.',
      metadataPill: 'DECRYPTING_BIO_SIGNATURE',
      price: '$32.00',
      addToCartLabel: 'ADD TO CART',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
  ],
  genomePhase: 'GENETIC ENGINEERING',
  genomeTitle: 'The Blending Genome',
  genomeIntro:
    'Each specimen is synthesized from verified origins, stress-tested across extraction protocols, and scored against our internal chromatography baseline before release.',
  genomeTabGallery: 'GALLERY VIEW',
  genomeTabDetailed: 'DETAILED ANALYSIS',
  genomeBackLabel: 'BACK TO GALLERY',
  genomeBackHref: '#vault',
  genomeGalleryIntro: 'Select a classified specimen to open its full genetic profile and sensory readout.',
  genomeGalleryCta: 'OPEN ANALYSIS',
  genomeMutationLabel: 'GEN IV MUTATION',
  genomeExtractionGradeLabel: 'EXTRACTION GRADE',
  genomeExtractionGradeValue: 'A+',
  genomeSpecimenTitle: 'Neon Synthesis',
  genomeSpecimenCode: 'FLT-002',
  genomeSpecimenStatus: 'STABLE',
  genomeGeneticSequenceLabel: 'GENETIC_SEQUENCE:',
  genomeGeneticSequenceText:
    'Rwanda Bourbon (55%) × Costa Rica Tarrazu (30%) × Colombia Pink Bourbon (15%)',
  genomeSensoryLabel: 'SENSORY_ANALYSIS:',
  genomeSensoryQuote:
    'Red berries, lemongrass, milk chocolate. Vibrant acidity with juicy mouthfeel and sweet finish.',
  genomeMetrics: [
    { label: 'ACIDITY INDEX', value: 88 },
    { label: 'BODY VISCOSITY', value: 55 },
    { label: 'SWEETNESS LEVEL', value: 82 },
    { label: 'COMPLEXITY SCORE', value: 91 },
  ],
  genomeStabilityLabel: 'STABILITY_INDEX:',
  genomeStabilityPercent: '96%',
  genomeStabilityStatus: 'OPTIMAL',
  genomeStabilityBar: 96,
  genomeRoastProfileLabel: 'ROAST PROFILE',
  genomeRoastProfileValue: 'City+',
  genomeMethodologyLabel: 'METHODOLOGY',
  genomeMethodologyValue: 'filter extraction',
  genomeComplexityLabel: 'COMPLEXITY',
  genomeComplexityValue: '91/100',
  genomeSpecimenCostLabel: 'SPECIMEN_COST',
  genomePriceDisplay: '$30.00',
  genomePerUnit: 'per 12oz',
  genomeAddToCartLabel: 'ADD TO CART',
  genomeLabNotesLabel: 'LAB_NOTES:',
  genomeLabNotes:
    'Extraction stability verified across three brew temperatures. Batch traceability locked to origin lots.',
  labPhase: 'RESEARCH',
  labTitle: 'The Lab',
  labSubtitle: 'Where science meets the art of coffee.',
  labBody:
    'Every batch is traced from seed to cup. Our lab instruments capture volatile aromatics, extraction yield, and particle distribution so we can reproduce profiles with molecular precision — without losing the human sensory panel that signs off every release.',
  labGridCards: [
    {
      title: 'Chromatography',
      description: 'Volatile mapping for every roast curve.',
      icon: 'flask',
    },
    {
      title: 'Particle lab',
      description: 'Grind distribution tuned to brew method.',
      icon: 'bean',
    },
    {
      title: 'Extraction matrix',
      description: 'TDS and yield tracked across bar pressure.',
      icon: 'chart',
    },
    {
      title: 'Sensory protocol',
      description: 'Blind cupping with calibrated scoring.',
      icon: 'atom',
    },
  ],
  archivesListPhase: 'FIELD NOTES',
  archivesListTitle: 'The Archives',
  archivesListIntro: 'Past experiments, protocols, and limited releases — indexed for research.',
  archivesPhilosophyTitle: 'Open Science Philosophy',
  archivesPhilosophyBody:
    'We publish raw data alongside marketing narratives. Every claim in our archive is traceable to a cupping session, a roast curve, or a producer invoice.\n\nOur field notes are living documents — updated when new harvests arrive or when protocols change — so researchers can cite the exact revision they used.',
  archivesFilterTabs: [
    { id: 'all', label: 'ALL' },
    { id: 'science', label: 'SCIENCE' },
    { id: 'economics', label: 'ECONOMICS' },
    { id: 'chemistry', label: 'CHEMISTRY' },
    { id: 'agriculture', label: 'AGRICULTURE' },
  ],
  archivesListRows: [
    {
      title: 'The True Cost of a Cup: A Global Analysis',
      filterKey: 'economics',
      category: 'ECONOMICS',
      dateDisplay: 'OCT 24, 2023',
      pagesLabel: '42 PGS',
      summary:
        'A longitudinal study mapping farm-gate prices, export logistics, and café margins across twelve origins — with transparent cost breakdowns per kilogram.',
      authors: 'Dr. Elena Voss, James Chen',
      readMinutes: 12,
      date: 'LOG-8821-A',
      href: '#',
    },
    {
      title: 'Molecular Acidity: Beyond the pH Scale',
      filterKey: 'chemistry',
      category: 'CHEMISTRY',
      dateDisplay: 'SEP 12, 2023',
      pagesLabel: '28 PGS',
      summary:
        'How chlorogenic acids and citric compounds interact during extraction — and why titration alone fails to predict perceived brightness in cup.',
      authors: 'Dr. A. Sterling, Dr. M. Okonkwo',
      readMinutes: 18,
      date: 'LOG-7704-B',
      href: '#',
    },
    {
      title: 'Altitude, Stress, and Bean Density: A Field Study',
      filterKey: 'agriculture',
      category: 'AGRICULTURE',
      dateDisplay: 'AUG 02, 2023',
      pagesLabel: '35 PGS',
      summary:
        'Three seasons of data from paired plots at 1,400m and 1,900m — correlating diurnal temperature swing with cell-wall density and solubility.',
      authors: 'Sarah Jenkins, Field Team',
      readMinutes: 15,
      date: 'LOG-6612-C',
      href: '#',
    },
    {
      title: 'Sensory Panel Calibration: Reproducibility in Q-Grading',
      filterKey: 'science',
      category: 'SCIENCE',
      dateDisplay: 'JUL 15, 2023',
      pagesLabel: '24 PGS',
      summary:
        'Inter-laboratory variance in scoring identical roasts — protocols to reduce drift and align calibration across remote cupping teams.',
      authors: 'CoffeeLab Sensory Lab',
      readMinutes: 9,
      date: 'LOG-5509-D',
      href: '#',
    },
  ],
  footerTagline: 'MOLECULAR ROASTERY // STATION_772',
  footerMission:
    'A decentralized collective of roasters and data scientists. Redefining extraction through radical transparency and digital precision.',
  footerMapTitle: 'SYSTEM_MAP',
  footerMapLinks: [
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  footerOpsTitle: 'OPERATIONS',
  footerOpsLinks: [
    { label: 'LOGISTICS', href: '#logistics' },
    { label: 'EXCHANGES', href: '#exchange' },
    { label: 'COLLECTIVE', href: '#collective' },
    { label: 'TERMINAL', href: '#terminal' },
  ],
  footerFeedTitle: 'NEURAL_FEED',
  footerFeedDescription: 'Receive extraction logs & sensory data streams',
  footerFeedPlaceholder: 'sample@mail.com',
  footerFeedSubmit: 'SECURE',
  footerFeedEncryption: 'ENCRYPTION ACTIVE',
  footerFeedSuccess: 'Opening your email app — send the message to subscribe.',
  footerCopyright: '© {year} CoffeeLab. All rights reserved.',
  neuralFeedMailSubject: 'CoffeeLab // Neural feed subscription',
  neuralFeedMailBodyIntro:
    'Please notify me about extraction logs and sensory data streams.',
}
