import type { Home } from '@/payload-types'

/**
 * German (de) seed strings for the `home` global — CoffeeLab molecular roastery.
 */
export const HOME_SEED_DE: Partial<Home> = {
  siteName: 'CoffeeLab',
  skipLinkLabel: 'Zum Hauptinhalt springen',
  accountAriaLabel: 'Konto',
  cartAriaLabel: 'Warenkorb',
  heroKicker: 'LABOR-PROTOKOLL // AKTIV',
  heroTitleLine1: 'MOLEKULAR',
  heroTitleLine2: 'RÖSTEREI',
  heroSubtitle:
    'Erkunde die biologische Grenze von Espresso- und Filter-Extraktion — digital synthetisiert.',
  heroAccentWord1: '',
  heroAccentWord2: '',
  heroPrimaryCtaLabel: 'SYSTEM_INITIALISIEREN',
  heroPrimaryCtaHref: '#roastery',
  heroSecondaryCtaLabel: 'ARCHIVE_SICHERN',
  heroSecondaryCtaHref: '#archives',
  navItems: [
    { label: 'SHOP', href: '#roastery' },
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  laboratoryPhase: 'LABOR-LADEN',
  laboratoryTitle: 'Ausgewählte Proben',
  laboratoryIntro:
    'Kuratierte Single Origins und präzisionsgeröstete Blends. Alle Proben auf Bestellung in unserem molekularen Labor geröstet.',
  laboratoryEmptyFilter: 'Keine Proben passen zu diesem Filter.',
  laboratoryPriceLabel: 'PREIS / 12OZ',
  laboratoryAddToCartAriaTemplate: '{title} in den Warenkorb legen',
  storeFilters: [
    { id: 'all', label: 'ALLE' },
    { id: 'bestseller', label: 'BESTSELLER' },
    { id: 'single-origin', label: 'SINGLE ORIGIN' },
    { id: 'espresso-blend', label: 'ESPRESSO BLEND' },
    { id: 'rare-varietal', label: 'SELTENE VARIETÄT' },
  ],
  protocolEyebrow: 'EXTRACTIONSPROTOKOLL',
  protocolTitle: 'Systemkalibrierung',
  brewEspressoLabel: 'ESPRESSO',
  brewFilterLabel: 'FILTER',
  geneticSection: {
    mediaTag: '32% GEWINN-RÜCKFÜHRUNG',
    phase: 'PHASE_01',
    title: 'Direkte genetische Beschaffung',
    body:
      'Wir analysieren die DNA jeder Mikrolot-Partie. Unsere Direktbeziehungen stellen sicher, dass Produzent:innen das Dreifache des Marktpreises erhalten.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  thermalSection: {
    mediaTag: '0,05°C VARIANZGRENZE',
    phase: 'PHASE_02',
    title: 'Thermische Röst-Präzision',
    body:
      'Unsere Smart-Röster erfassen 1.200 Datenpunkte pro Sekunde — genau am chemischen Übergang, an dem Säure in komplexe Süße übergeht.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  valueSection: {
    mediaTag: '100% KOSTENTRANSPARENZ',
    phase: 'PHASE_03',
    title: 'Transparenter Werte-Index',
    body:
      'Kein Marketing-Blabla. Wir legen Kosten offen: Rohkaffee, Logistik, Röstenergie — fair kalkuliert.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  precisionPhase: 'PRECISION LAB',
  precisionTitle: 'Molekulare Anpassung',
  precisionIntro:
    'Justiere die chemischen Variablen. Als Expert:in steuerst du die Extraktionskurven für das Filterprofil.',
  precisionPanelTitle: 'EXTRACTION LAB',
  precisionStatusPrefix: 'STATUS: AKTIV //',
  axisRoast: 'RÖSTUNG',
  axisAcidity: 'SÄURE',
  axisBody: 'KÖRPER',
  axisSweetness: 'SÜSSE',
  axisComplexity: 'KOMPLEXITÄT',
  matrixHeading: 'EXTRACTION MATRIX:',
  matrixTagsEspresso: [
    { text: 'MAILLARD-FÜLLE' },
    { text: 'KARAMELLISIERTER ABKLANG' },
    { text: 'HOHE VISKOSITÄT' },
  ],
  matrixTagsFilter: [
    { text: 'ZITRISCHE HELLE NOTEN' },
    { text: 'KARAMELLISIERTER ABKLANG' },
    { text: 'FLÜCHTIGE AROMEN' },
  ],
  synthesizeButton: 'GESCHMACKSPROFIL SYNTHETISIEREN',
  scanStats: [
    { template: 'SCAN_UID: X-992' },
    { template: 'BEAM_TEMP: {beam}°C' },
    { template: 'WATER_V: {water}%' },
  ],
  roastSliderLabel: 'Röstziel setzen',
  radarAriaLabel: 'Live-Flavor-Radar',
  flavorNote: 'Das Geschmacksprofil aktualisiert sich in Echtzeit mit der Röstung.',
  blendingPhase: 'GENETIC FUSION',
  blendingTitle: 'Die Blending-Kammer',
  blendingIntro: 'Synthese seltener Mikrolots — optimiert für Klarheit des Terroirs.',
  blendingTabExpert: 'EXPERTEN-KURATION',
  blendingTabManual: 'MANUELLE MONTAGE',
  blendingExpertCards: [
    {
      intensityLabel: 'ÄTHERISCHE INTENSITÄT',
      title: 'Prism Clarity',
      sensoryFilter: '"Teeartiger Körper, Jasmin, weiße Pfirsichsäure."',
      sensoryEspresso: '"Dichte Crema, Schokolade, konzentrierte Süße."',
      geneticBase: 'Äthiopien Yirgacheffe (gewaschen)',
      methodologyFilter: 'FILTER-EXTRACTION',
      methodologyEspresso: 'ESPRESSO-EXTRACTION',
      price: '$28.00',
      cta: 'IN DEN WARENKORB',
    },
    {
      intensityLabel: 'VIBRANTE INTENSITÄT',
      title: 'Neon Horizon',
      sensoryFilter: '"Beeren, spritzige Säure, Honigabgang."',
      sensoryEspresso: '"Schwerer Körper, karamellisierte Süße, sirupartiger Abgang."',
      geneticBase: 'Kenia Nyeri + Kolumbien Pink Bourbon',
      methodologyFilter: 'FILTER-EXTRACTION',
      methodologyEspresso: 'ESPRESSO-EXTRACTION',
      price: '$25.00',
      cta: 'IN DEN WARENKORB',
    },
  ],
  manualAssemblerTitle: 'GENETISCHER ASSEMBLER',
  manualAssemblerProtocolPrefix: 'PROTOKOLL: MANUELL //',
  manualRecalibrate: 'NEU KALIBRIEREN',
  manualRowsEspresso: [
    { code: 'MOGIANA // PROBE', name: 'Brasilien Santos' },
    { code: 'MALABAR // PROBE', name: 'Indien Monsooned' },
    { code: 'LAB SELECT // PROBE', name: 'Dark Roast Blend' },
  ],
  manualRowsFilter: [
    { code: 'GUJI // PROBE', name: 'Äthiopien Heirloom' },
    { code: 'GEISHA // PROBE', name: 'Panama Geisha' },
    { code: 'LAB SELECT // PROBE', name: 'Light Roast Blend' },
  ],
  saturationLabel: 'SÄTTIGUNG',
  stabilityLabel: 'STABILITÄTSPRÜFUNG',
  stabilityLocked: 'SYSTEM_GESPERRT',
  stabilityCalibrating: 'KALIBRIERUNG...',
  finalizeAssembly: 'MONTAGE ABSCHLIESSEN',
  vaultPhase: 'SENSORISCHE ENTKOPPLUNG',
  vaultTitle: 'Klassifiziertes Archiv',
  vaultIntro: 'Zugang zu den exklusivsten Bohnen unserer Kollektion.',
  vaultCuppingLabel: 'CUPPING-SCORE',
  vaultSpecimenYear: 'PROBE // 2026',
  vaultMetadataLabel: 'METADATEN:',
  vaultMetadataValue: 'VERSCHLÜSSELT_FÜR_FORSCHUNG',
  vaultPriceLabel: 'PROBENKOSTEN',
  vaultCards: [
    {
      score: '91.5',
      title: 'PROTOKOLL X-771',
      label: 'EXPERIMENTELLES PROFIL',
      originLine: 'Äthiopien · Heirloom',
      roastLine: 'Hell — expressiv',
      flavorLine: 'Jasmin, Bergamotte, Nektarine',
      description:
        'Ein Profil an der Grenze der Wahrnehmung. Hohe thermische Variabilität während der Röstung.',
      metadataPill: 'ENTSCHLÜSSELUNG_BIO_SIGNATUR',
      price: '$32.00',
      addToCartLabel: 'IN DEN WARENKORB',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
    {
      score: '89.0',
      title: 'PROTOKOLL X-442',
      label: 'ANAEROBES MIKROLOT',
      originLine: 'Höhenlage nicht offengelegt',
      roastLine: 'Mittel — entwickelt',
      flavorLine: 'Kakao, rote Beere, Melasse',
      description:
        'Geheim gelegene Hochland-Parzelle. Identität verborgen gegen Erwartungsbias.',
      metadataPill: 'ENTSCHLÜSSELUNG_BIO_SIGNATUR',
      price: '$32.00',
      addToCartLabel: 'IN DEN WARENKORB',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
    {
      score: '92.2',
      title: 'PROTOKOLL X-901',
      label: 'CARBONIC MACERATION',
      originLine: 'Panama · Gesha',
      roastLine: 'Hell — omni',
      flavorLine: 'Tropisch, Schaumwein, Seide',
      description: 'Höhepunkt unserer Laborarbeiten. Reine molekulare Terroir-Expression.',
      metadataPill: 'ENTSCHLÜSSELUNG_BIO_SIGNATUR',
      price: '$32.00',
      addToCartLabel: 'IN DEN WARENKORB',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
  ],
  genomePhase: 'GENTECHNIK',
  genomeTitle: 'Das Blending-Genom',
  genomeIntro:
    'Jede Probe wird aus verifizierten Ursprüngen synthetisiert, über Extraktionsprotokolle stresstestet und gegen unsere interne Chromatographie-Baseline bewertet.',
  genomeTabGallery: 'GALERIE',
  genomeTabDetailed: 'DETAILANALYSE',
  genomeBackLabel: 'ZURÜCK ZUR GALERIE',
  genomeBackHref: '#vault',
  genomeGalleryIntro: 'Wähle eine klassifizierte Probe, um das vollständige Genprofil und die sensorische Auswertung zu öffnen.',
  genomeGalleryCta: 'ANALYSE ÖFFNEN',
  genomeMutationLabel: 'GEN IV MUTATION',
  genomeExtractionGradeLabel: 'EXTRACTIONSGRAD',
  genomeExtractionGradeValue: 'A+',
  genomeSpecimenTitle: 'Neon Synthesis',
  genomeSpecimenCode: 'FLT-002',
  genomeSpecimenStatus: 'STABIL',
  genomeGeneticSequenceLabel: 'GENETISCHE_SEQUENZ:',
  genomeGeneticSequenceText:
    'Rwanda Bourbon (55%) × Costa Rica Tarrazu (30%) × Colombia Pink Bourbon (15%)',
  genomeSensoryLabel: 'SENSORIK:',
  genomeSensoryQuote:
    'Rote Beeren, Zitronengras, Milchschokolade. Lebendige Säure mit saftigem Mundgefühl und süßem Abgang.',
  genomeMetrics: [
    { label: 'SÄURE-INDEX', value: 88 },
    { label: 'KÖRPER-VISKOSITÄT', value: 55 },
    { label: 'SÜSSE', value: 82 },
    { label: 'KOMPLEXITÄT', value: 91 },
  ],
  genomeStabilityLabel: 'STABILITÄTSINDEX:',
  genomeStabilityPercent: '96%',
  genomeStabilityStatus: 'OPTIMAL',
  genomeStabilityBar: 96,
  genomeRoastProfileLabel: 'RÖSTPROFIL',
  genomeRoastProfileValue: 'City+',
  genomeMethodologyLabel: 'METHODOLOGIE',
  genomeMethodologyValue: 'Filter-Extraktion',
  genomeComplexityLabel: 'KOMPLEXITÄT',
  genomeComplexityValue: '91/100',
  genomeSpecimenCostLabel: 'PROBENKOSTEN',
  genomePriceDisplay: '30,00 €',
  genomePerUnit: 'pro 12oz',
  genomeAddToCartLabel: 'IN DEN WARENKORB',
  genomeLabNotesLabel: 'LABORNOTIZEN:',
  genomeLabNotes:
    'Extraktionsstabilität über drei Brühtemperaturen verifiziert. Chargen-Rückverfolgbarkeit an Ursprungslots gekoppelt.',
  labPhase: 'FORSCHUNG',
  labTitle: 'Das Labor',
  labSubtitle: 'Wo Wissenschaft auf die Kunst des Kaffees trifft.',
  labBody:
    'Jede Charge wird von der Bohne bis zur Tasse verfolgt. Unsere Instrumente erfassen volatile Aromastoffe, Extraktionsausbeute und Mahlgrad — damit wir Profile molekular reproduzieren können, ohne das menschliche Cupping-Panel zu ersetzen.',
  labGridCards: [
    {
      title: 'Chromatographie',
      description: 'Volatile Karten für jede Röstkurve.',
      icon: 'flask',
    },
    {
      title: 'Partikellabor',
      description: 'Mahlverteilung abgestimmt auf die Brühmethode.',
      icon: 'bean',
    },
    {
      title: 'Extraktionsmatrix',
      description: 'TDS und Ausbeute über den Bar-Druck.',
      icon: 'chart',
    },
    {
      title: 'Sensorik-Protokoll',
      description: 'Blind-Cupping mit kalibriertem Scoring.',
      icon: 'atom',
    },
  ],
  archivesListPhase: 'FELDNOTIZEN',
  archivesListTitle: 'Das Archiv',
  archivesListIntro: 'Vergangene Experimente, Protokolle und Limitierungen — indexiert für die Forschung.',
  archivesPhilosophyTitle: 'Open-Science-Philosophie',
  archivesPhilosophyBody:
    'Wir veröffentlichen Rohdaten neben Marketing-Erzählungen. Jede Aussage in unserem Archiv ist zurückführbar auf eine Cupping-Session, eine Röstkurve oder eine Produzentenrechnung.\n\nUnsere Feldnotizen sind lebendige Dokumente — aktualisiert bei neuer Ernte oder geänderten Protokollen — damit Forschende die exakte Revision zitieren können.',
  archivesFilterTabs: [
    { id: 'all', label: 'ALLE' },
    { id: 'science', label: 'WISSENSCHAFT' },
    { id: 'economics', label: 'ÖKONOMIE' },
    { id: 'chemistry', label: 'CHEMIE' },
    { id: 'agriculture', label: 'LANDWIRTSCHAFT' },
  ],
  archivesListRows: [
    {
      title: 'Die wahren Kosten einer Tasse: eine globale Analyse',
      filterKey: 'economics',
      category: 'ÖKONOMIE',
      dateDisplay: '24. OKT. 2023',
      pagesLabel: '42 S.',
      summary:
        'Langzeitstudie zu Farmgate-Preisen, Exportlogistik und Café-Margen in zwölf Ursprüngen — mit transparenten Kostenaufschlüsselungen pro Kilogramm.',
      authors: 'Dr. Elena Voss, James Chen',
      readMinutes: 12,
      date: 'LOG-8821-A',
      href: '#',
    },
    {
      title: 'Molekulare Säure: jenseits der pH-Skala',
      filterKey: 'chemistry',
      category: 'CHEMIE',
      dateDisplay: '12. SEP. 2023',
      pagesLabel: '28 S.',
      summary:
        'Wie Chlorogensäuren und Zitronensäure bei der Extraktion interagieren — und warum Titration allein die wahrgenommene Lebendigkeit nicht vorhersagt.',
      authors: 'Dr. A. Sterling, Dr. M. Okonkwo',
      readMinutes: 18,
      date: 'LOG-7704-B',
      href: '#',
    },
    {
      title: 'Höhe, Stress und Bohnendichte: eine Feldstudie',
      filterKey: 'agriculture',
      category: 'LANDWIRTSCHAFT',
      dateDisplay: '02. AUG. 2023',
      pagesLabel: '35 S.',
      summary:
        'Drei Ernten mit Daten von parzellierten Flächen auf 1.400 m und 1.900 m — Korrelation von Temperaturamplitude mit Zellwanddichte und Löslichkeit.',
      authors: 'Sarah Jenkins, Field Team',
      readMinutes: 15,
      date: 'LOG-6612-C',
      href: '#',
    },
    {
      title: 'Sensory-Panel-Kalibrierung: Reproduzierbarkeit im Q-Grading',
      filterKey: 'science',
      category: 'WISSENSCHAFT',
      dateDisplay: '15. JUL. 2023',
      pagesLabel: '24 S.',
      summary:
        'Varianz zwischen Laboren bei identischen Röstungen — Protokolle zur Reduktion von Drift und zur Abstimmung entfernter Cupping-Teams.',
      authors: 'CoffeeLab Sensory Lab',
      readMinutes: 9,
      date: 'LOG-5509-D',
      href: '#',
    },
  ],
  operationsPhase: 'PHASE_06 // OPS',
  operationsTitle: 'OPERATIONS',
  operationsIntro:
    'Lieferketten-Telemetrie, Rohkaffee-Börse, Kollektiv-Governance und Live-Terminal — vereint in einer operativen Schicht.',
  operationsPanels: [
    {
      anchor: 'logistics',
      label: 'LOGISTICS',
      status: 'NOMINAL',
      title: 'Lieferkette vom Ursprung zum Hafen',
      body: 'Jede Sendung wird am Farmgate mit Feuchte, Dichte und GPS markiert. Kühlketten-Sensoren streamen Temperaturdaten über Rhein-Korridore bis zum Konsolidierungsknoten Köln — volle Rückverfolgbarkeit von der Kirsche bis zum Container.',
      metrics: [
        { key: 'AKTIVE_ROUTEN', value: '14' },
        { key: 'URSPRUNGSKNOTEN', value: '8' },
        { key: 'Ø_TRANSIT', value: '18,4d' },
        { key: 'KÜHLKETTE', value: '99,2%' },
      ],
      feed: [
        { code: 'LOG-4102', message: 'ETA bestätigt — Huila → Köln' },
        { code: 'LOG-4098', message: 'Container CLB-KLN1 Zoll frei — Eingang Köln' },
        { code: 'LOG-4091', message: 'Feuchtesensor-Alarm behoben — Yirgacheffe Los #44' },
        { code: 'LOG-4087', message: 'Neue Route — Sidama → Köln direkt' },
      ],
      ctaLabel: 'SENDUNG_VERFOLGEN',
      ctaHref: '#',
    },
    {
      anchor: 'exchange',
      label: 'EXCHANGES',
      status: 'OFFEN',
      title: 'Rohkaffee-Börse',
      body: 'Peer-to-Peer-Loshandel mit transparenten Cupping-Scores, Farmgate-Preisen und Treuhand-Abwicklung. Röster:innen bieten auf verifizierte Lose mit vollständigen sensorischen Metadaten — ohne undurchsichtige Zwischenhändler.',
      metrics: [
        { key: 'LIVE_LOSE', value: '37' },
        { key: 'Ø_SPREAD', value: '±2,1%' },
        { key: 'ABRECHNUNG', value: 'T+2' },
        { key: 'VOLUMEN_24H', value: '4,2t' },
      ],
      feed: [
        { code: 'EXC-2201', message: 'Los #ETH-019 Gebot angenommen — 2.400 kg @ $4,82/lb' },
        { code: 'EXC-2198', message: 'Neues Listing — Gesha, Boquete, 87,5 SCA' },
        { code: 'EXC-2194', message: 'Treuhand freigegeben — COL-HUI-772 → Station_KLN' },
        { code: 'EXC-2189', message: 'Preisindex aktualisiert — Arabica FOB +0,3%' },
      ],
      ctaLabel: 'MARKT_ANSEHEN',
      ctaHref: '#',
    },
    {
      anchor: 'collective',
      label: 'COLLECTIVE',
      status: 'WACHSEND',
      title: 'Röster-Kollektiv-Netzwerk',
      body: 'Ein dezentrales Kollektiv aus Röster:innen und Datenwissenschaftler:innen, das Röstkurven, Sensory-Panels und Ursprungsdaten teilt. Mitglieder liefern anonymisierte Extraktionsdaten im Tausch gegen netzweite Kalibrierungsprotokolle.',
      metrics: [
        { key: 'MITGLIEDER', value: '128' },
        { key: 'REGIONEN', value: '22' },
        { key: 'CUPPINGS_MO', value: '340' },
        { key: 'OFFENE_ROLLEN', value: '6' },
      ],
      feed: [
        { code: 'COL-1104', message: 'HQ-Knoten verifiziert — Köln, DE (Station_KLN)' },
        { code: 'COL-1099', message: 'Geteilte Röstkurve — Äthiopien Natural, 8:42 Entwicklung' },
        { code: 'COL-1095', message: 'Governance-Abstimmung — Q3-Transparenzbericht angenommen' },
        { code: 'COL-1091', message: 'Sensory-Panel-Sync — 14 Labore kalibriert' },
      ],
      ctaLabel: 'KOLLEKTIV_BEITRETEN',
      ctaHref: '#',
    },
    {
      anchor: 'terminal',
      label: 'TERMINAL',
      status: 'ONLINE',
      title: 'Kommando-Terminal',
      body: 'Live-Systemtelemetrie für Röstbetrieb — API-Status, Extraktionssitzungen und Sensorströme. Autorisierte Operatoren können Röstlogs abfragen, Sensory-Datensätze laden und Kalibrierungsprotokolle senden.',
      metrics: [
        { key: 'VERFÜGBARKEIT', value: '99,97%' },
        { key: 'SITZUNGEN', value: '42' },
        { key: 'API_CALLS', value: '18,4k' },
        { key: 'LATENZ', value: '12ms' },
      ],
      feed: [
        { code: 'SYS', message: '> auth bestätigt — Operator-Sitzung aktiv' },
        { code: 'SYS', message: '> roast_log --tail CLB-KLN1 — streaming…' },
        { code: 'SYS', message: '> sensor_mesh status: alle Knoten nominal' },
        { code: 'SYS', message: '> warte auf Eingabe…' },
      ],
      ctaLabel: 'TERMINAL_ÖFFNEN',
      ctaHref: '#',
    },
  ],
  footerTagline: 'MOLEKULAR-RÖSTEREI // KÖLN',
  footerMission:
    'Ein dezentrales Kollektiv aus Röster:innen und Datenwissenschaftler:innen mit Sitz in Köln. Extraktion neu definiert — radikal transparent, digital präzise.',
  footerMapTitle: 'SYSTEM_MAP',
  footerMapLinks: [
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  footerOpsTitle: 'OPERATIONS',
  footerOpsLinks: [
    { label: 'LOGISTICS', href: '#logistics' },
    { label: 'EXCHANGES', href: '#exchange' },
    { label: 'COLLECTIVE', href: '#collective' },
    { label: 'TERMINAL', href: '#terminal' },
  ],
  footerFeedTitle: 'NEURAL_FEED',
  footerFeedDescription: 'Extraktions-Logs & sensorische Datenströme erhalten',
  footerFeedPlaceholder: 'sample@mail.com',
  footerFeedSubmit: 'SICHERN',
  footerFeedEncryption: 'VERSCHLÜSSELUNG AKTIV',
  footerFeedSuccess: 'E-Mail-App öffnet — Nachricht senden zum Abonnieren.',
  footerCopyright: '© {year} CoffeeLab. Alle Rechte vorbehalten.',
  neuralFeedMailSubject: 'CoffeeLab // Neural Feed',
  neuralFeedMailBodyIntro:
    'Bitte über Extraktions-Logs und sensorische Datenströme informieren.',
  labStats: [
    { value: '50+', label: 'PRODUKTE', icon: 'box' },
    { value: '92.5', label: 'QUALITÄTSSCORE', icon: 'medal' },
    { value: '4.8', label: 'Ø BEWERTUNG', icon: 'star' },
    { value: '5.200+', label: 'ZUFRIEDENE KUND:INNEN', icon: 'trend' },
  ],
}
